[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
esports_manager_contract = "2KBakNVa6xLxp6uQsgHhikrknw1pkjkS2f6ZGKtV5BzZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/wanaqil/devnet-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"